apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
data:
  SPRING_PROFILES_ACTIVE: prod
  PORTFOLIO_SITE_URL: http://localhost:30080
  MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://localhost:4318/v1/traces
