apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kubernetes

images:
  - name: ghcr.io/codernawaki/portfolio
    newName: portfolio
    newTag: minikube

patches:
  - path: app-service-patch.yaml
  - path: app-deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: app-ingress-delete.yaml
  - path: app-hpa-delete.yaml
