apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
type: Opaque
stringData:
  PORTFOLIO_ADMIN_USERNAME: REPLACE_ME_ADMIN_USERNAME
  PORTFOLIO_ADMIN_PASSWORD: REPLACE_ME_ADMIN_PASSWORD
  SPRING_DATASOURCE_USERNAME: REPLACE_ME_DB_USERNAME
  SPRING_DATASOURCE_PASSWORD: REPLACE_ME_DB_PASSWORD
  SPRING_MAIL_USERNAME: REPLACE_ME_SMTP_USERNAME
  SPRING_MAIL_PASSWORD: REPLACE_ME_SMTP_PASSWORD
  PORTFOLIO_CONTACT_NOTIFICATION_EMAIL: REPLACE_ME_NOTIFICATION_EMAIL
  POSTGRES_DB: portfolio
  POSTGRES_USER: REPLACE_ME_DB_USERNAME
  POSTGRES_PASSWORD: REPLACE_ME_DB_PASSWORD
