apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
type: Opaque
stringData:
  PORTFOLIO_ADMIN_USERNAME: change-me
  PORTFOLIO_ADMIN_PASSWORD: change-me
  SPRING_DATASOURCE_USERNAME: portfolio_user
  SPRING_DATASOURCE_PASSWORD: change-me
  SPRING_MAIL_USERNAME: change-me
  SPRING_MAIL_PASSWORD: change-me
  PORTFOLIO_CONTACT_NOTIFICATION_EMAIL: hello@example.com
  POSTGRES_DB: portfolio
  POSTGRES_USER: portfolio_user
  POSTGRES_PASSWORD: change-me
