create table if not exists contact_submissions (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(150) not null,
    message varchar(2000) not null,
    admin_note varchar(1200),
    created_at timestamp with time zone not null,
    status varchar(20) not null
);

create index if not exists idx_contact_submissions_created_at
    on contact_submissions (created_at desc);
