create table if not exists articles (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    slug varchar(200) not null unique,
    content text not null,
    excerpt varchar(500),
    tags varchar(500),
    status varchar(20) not null default 'DRAFT',
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    published_at timestamp with time zone
);

create index if not exists idx_articles_slug on articles (slug);
create index if not exists idx_articles_status on articles (status);
create index if not exists idx_articles_published_at on articles (published_at desc);
