create table if not exists article_likes (
    id bigint generated by default as identity primary key,
    article_id bigint not null references articles(id) on delete cascade,
    ip_address varchar(45) not null,
    created_at timestamp with time zone not null,
    unique (article_id, ip_address)
);

create index if not exists idx_article_likes_article_id on article_likes (article_id);
