create table if not exists article_comments (
    id bigint generated by default as identity primary key,
    article_id bigint not null references articles(id) on delete cascade,
    parent_id bigint references article_comments(id) on delete cascade,
    author varchar(100) not null,
    content varchar(2000) not null,
    created_at timestamp with time zone not null
);

create index if not exists idx_article_comments_article_id on article_comments (article_id);
create index if not exists idx_article_comments_parent_id on article_comments (parent_id);
