create table if not exists article_comment_likes (
    id bigint generated by default as identity primary key,
    comment_id bigint not null references article_comments(id) on delete cascade,
    ip_address varchar(45) not null,
    created_at timestamp with time zone not null,
    unique (comment_id, ip_address)
);

create index if not exists idx_comment_likes_comment_id on article_comment_likes (comment_id);
