create table if not exists blog_notifications (
    id bigint generated by default as identity primary key,
    article_id bigint not null unique,
    article_title varchar(200) not null,
    article_slug varchar(200) not null,
    message varchar(300) not null,
    published_at timestamp with time zone not null,
    created_at timestamp with time zone not null
);

create index if not exists idx_blog_notifications_published_at
    on blog_notifications (published_at desc);
