name: Java CI with Gradle

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Run Tests
      run: ./gradlew test
      env:
        PORTFOLIO_ADMIN_USERNAME: test-admin
        PORTFOLIO_ADMIN_PASSWORD: test-password
        SPRING_MAIL_USERNAME: ""
        SPRING_MAIL_PASSWORD: ""
        PORTFOLIO_CONTACT_NOTIFICATION_EMAIL: ""
